/** BuchoDenti — backend based on GALADENT+ master */
const SHEET_ID = '1Eo39mJiL8If-vj9BRLRv9wGMXLcqFdcVCxT6LW5lC_o';
const CALENDAR_ID = 'ВСТАВЬ_СЮДА_BUCHODENTI_CALENDAR_ID';
const WORK_DAYS=[1,2,3,4,5,6];
const WORK_START_HOUR=10;
const WORK_END_HOUR=19;
const SLOT_MINUTES=30;
const SHEET_NAME='Bookings';
const COLUMNS=['id','createdAt','date','time','name','lastName','phone','tooth','procedure','note','price','status','calendarEventId','source'];
function doGet(){return jsonOut({ok:true,clinic:'BuchoDenti',message:'BuchoDenti Booking API работает'});}
function doPost(e){let p;try{p=JSON.parse(e.postData.contents)}catch(err){return jsonOut({ok:false,error:'Некорректный запрос.'})}try{switch(p.action){case'getSlots':return jsonOut(getSlots(p));case'bookOnline':return jsonOut(bookOnline(p,'online'));case'bookManual':return jsonOut(bookOnline(p,'staff'));case'cancel':return jsonOut(cancelVisit(p));case'reschedule':return jsonOut(rescheduleVisit(p));case'updateVisit':return jsonOut(updateVisit(p));case'listVisits':return jsonOut(listVisits(p));case'searchPatient':return jsonOut(searchPatient(p));default:return jsonOut({ok:false,error:'Неизвестное действие: '+p.action})}}catch(err){return jsonOut({ok:false,error:'Ошибка сервера: '+err.message})}}
function jsonOut(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function getSheet(){const ss=SpreadsheetApp.openById(SHEET_ID);let sh=ss.getSheetByName(SHEET_NAME);if(!sh){sh=ss.insertSheet(SHEET_NAME);sh.appendRow(COLUMNS);sh.getRange('C:D').setNumberFormat('@')}return sh}
function readAllRows(){const v=getSheet().getDataRange().getValues(),rows=[];for(let i=1;i<v.length;i++){const r={};COLUMNS.forEach((c,j)=>r[c]=v[i][j]);r._row=i+1;rows.push(r)}return rows}
function writeRow(o){getSheet().appendRow(COLUMNS.map(c=>o[c]!==undefined?o[c]:''))}
function updateRowByIndex(i,p){const sh=getSheet();COLUMNS.forEach((c,j)=>{if(p[c]!==undefined)sh.getRange(i,j+1).setValue(String(p[c]))})}
function findRowById(id){return readAllRows().find(r=>String(r.id)===String(id))||null}
function pad2(n){return(n<10?'0':'')+n}
function generateAllSlots(ds){const d=new Date(ds+'T00:00:00');if(!WORK_DAYS.includes(d.getDay()))return[];const out=[];let h=WORK_START_HOUR,m=0;while(h<WORK_END_HOUR){out.push(pad2(h)+':'+pad2(m));m+=SLOT_MINUTES;if(m>=60){m-=60;h++}}return out}
function getSlots(p){if(!p.date)return{ok:false,error:'Не указана дата.'};const all=generateAllSlots(p.date);if(!all.length)return{ok:true,data:[]};const taken=readAllRows().filter(r=>r.date===p.date&&r.status!=='отменено').map(r=>r.time);let free=all.filter(s=>!taken.includes(s));const now=new Date(),today=now.getFullYear()+'-'+pad2(now.getMonth()+1)+'-'+pad2(now.getDate());if(p.date===today)free=free.filter(s=>{const a=s.split(':').map(Number);return a[0]>now.getHours()||(a[0]===now.getHours()&&a[1]>now.getMinutes())});return{ok:true,data:free}}
function bookOnline(p,source){if(!p.date||!p.time||!p.name||!p.phone)return{ok:false,error:'Заполните обязательные поля.'};const lock=LockService.getScriptLock();try{lock.waitLock(10000)}catch(e){return{ok:false,error:'Сервер занят, попробуйте ещё раз.'}}try{if(readAllRows().some(r=>r.date===p.date&&r.time===p.time&&r.status!=='отменено'))return{ok:false,error:'Это время уже занято.'};const id='v'+Date.now(),title=(p.lastName||'')+' '+p.name+(p.procedure?' — '+p.procedure:''),desc=['Телефон: '+p.phone,p.note?'Заметка: '+p.note:(p.complaint?'Комментарий: '+p.complaint:''),p.price?'Сумма: '+p.price+' ₾':''].filter(Boolean).join('\n'),eventId=createCalendarEvent(p.date,p.time,title,desc);writeRow({id,createdAt:new Date().toISOString(),date:p.date,time:p.time,name:p.name,lastName:p.lastName||'',phone:p.phone,tooth:p.tooth||'',procedure:p.procedure||'',note:p.note||p.complaint||'',price:p.price||'',status:'новая',calendarEventId:eventId,source});return{ok:true,id}}finally{lock.releaseLock()}}
function createCalendarEvent(date,time,title,description){const cal=CalendarApp.getCalendarById(CALENDAR_ID);if(!cal)throw new Error('Календарь не найден — проверь CALENDAR_ID.');const a=time.split(':').map(Number),start=new Date(date+'T00:00:00');start.setHours(a[0],a[1],0,0);const end=new Date(start.getTime()+SLOT_MINUTES*60000);return cal.createEvent(title,start,end,{description}).getId()}
function deleteCalendarEventSafe(id){if(!id)return;try{const e=CalendarApp.getCalendarById(CALENDAR_ID).getEventById(id);if(e)e.deleteEvent()}catch(e){}}
function cancelVisit(p){const r=findRowById(p.id);if(!r)return{ok:false,error:'Запись не найдена.'};updateRowByIndex(r._row,{status:'отменено'});deleteCalendarEventSafe(r.calendarEventId);return{ok:true}}
function rescheduleVisit(p){const r=findRowById(p.id);if(!r)return{ok:false,error:'Запись не найдена.'};if(readAllRows().some(x=>x.id!==r.id&&x.date===p.date&&x.time===p.time&&x.status!=='отменено'))return{ok:false,error:'Это время уже занято.'};deleteCalendarEventSafe(r.calendarEventId);const title=(r.lastName||'')+' '+(r.name||'')+(r.procedure?' — '+r.procedure:''),eid=createCalendarEvent(p.date,p.time,title,'Телефон: '+r.phone+'\n'+(r.note||''));updateRowByIndex(r._row,{date:p.date,time:p.time,calendarEventId:eid});return{ok:true}}
function updateVisit(p){const r=findRowById(p.id);if(!r)return{ok:false,error:'Запись не найдена.'};updateRowByIndex(r._row,{tooth:p.tooth||'',procedure:p.procedure||'',note:p.note||'',price:p.price||''});return{ok:true}}
function stripInternal(r){const c=Object.assign({},r);delete c._row;return c}
function listVisits(p){return{ok:true,data:readAllRows().filter(r=>r.date===p.date).sort((a,b)=>String(a.time).localeCompare(String(b.time))).map(stripInternal)}}
function searchPatient(p){if(!p.phone)return{ok:false,error:'Укажите телефон.'};const rows=readAllRows().filter(r=>String(r.phone).includes(p.phone));if(!rows.length)return{ok:true,data:{found:false}};const last=rows[rows.length-1];return{ok:true,data:{found:true,name:last.name,lastName:last.lastName,visits:rows.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(stripInternal)}}}
