/** BuchoDenti — backend based on GALADENT+ master */
const SHEET_ID='1Eo39mJiL8If-vj9BRLRv9wGMXLcqFdcVCxT6LW5lC_o';
const CALENDAR_ID='ВСТАВЬ_СЮДА_BUCHODENTI_CALENDAR_ID';
const WORK_DAYS=[1,2,3,4,5,6],WORK_START_HOUR=10,WORK_END_HOUR=19,SLOT_MINUTES=30,SHEET_NAME='Bookings';
const COLUMNS=['id','createdAt','date','time','name','lastName','phone','tooth','procedure','note','price','status','calendarEventId','source'];
function doGet(){return jsonOut({ok:true,clinic:'BuchoDenti',message:'BuchoDenti Booking API работает'})}
function doPost(e){let p;try{p=JSON.parse(e.postData.contents)}catch(x){return jsonOut({ok:false,error:'Некорректный запрос.'})}try{switch(p.action){case'getSlots':return jsonOut(getSlots(p));case'bookOnline':return jsonOut(book(p,'online'));case'bookManual':return jsonOut(book(p,'staff'));case'cancel':return jsonOut(cancel(p));case'reschedule':return jsonOut(reschedule(p));case'updateVisit':return jsonOut(updateVisit(p));case'listVisits':return jsonOut(listVisits(p));case'searchPatient':return jsonOut(searchPatient(p));default:return jsonOut({ok:false,error:'Неизвестное действие: '+p.action})}}catch(x){return jsonOut({ok:false,error:'Ошибка сервера: '+x.message})}}
function jsonOut(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function sheet(){const ss=SpreadsheetApp.openById(SHEET_ID);let s=ss.getSheetByName(SHEET_NAME);if(!s){s=ss.insertSheet(SHEET_NAME);s.appendRow(COLUMNS);s.getRange('C:D').setNumberFormat('@')}return s}
function rows(){const v=sheet().getDataRange().getValues(),a=[];for(let i=1;i<v.length;i++){let r={};COLUMNS.forEach((c,j)=>r[c]=v[i][j]);r._row=i+1;a.push(r)}return a}
function add(o){sheet().appendRow(COLUMNS.map(c=>o[c]!==undefined?o[c]:''))}function patch(i,p){const s=sheet();COLUMNS.forEach((c,j)=>{if(p[c]!==undefined)s.getRange(i,j+1).setValue(String(p[c]))})}function byId(id){return rows().find(r=>String(r.id)===String(id))||null}function p2(n){return(n<10?'0':'')+n}
function allSlots(ds){const d=new Date(ds+'T00:00:00');if(!WORK_DAYS.includes(d.getDay()))return[];let a=[],h=WORK_START_HOUR,m=0;while(h<WORK_END_HOUR){a.push(p2(h)+':'+p2(m));m+=SLOT_MINUTES;if(m>=60){m-=60;h++}}return a}
function getSlots(p){if(!p.date)return{ok:false,error:'Не указана дата.'};let a=allSlots(p.date);const t=rows().filter(r=>r.date===p.date&&r.status!=='отменено').map(r=>r.time);a=a.filter(x=>!t.includes(x));const n=new Date(),td=n.getFullYear()+'-'+p2(n.getMonth()+1)+'-'+p2(n.getDate());if(p.date===td)a=a.filter(x=>{let q=x.split(':').map(Number);return q[0]>n.getHours()||(q[0]===n.getHours()&&q[1]>n.getMinutes())});return{ok:true,data:a}}
function book(p,source){if(!p.date||!p.time||!p.name||!p.phone)return{ok:false,error:'Заполните обязательные поля.'};const l=LockService.getScriptLock();try{l.waitLock(10000)}catch(e){return{ok:false,error:'Сервер занят, попробуйте ещё раз.'}}try{if(rows().some(r=>r.date===p.date&&r.time===p.time&&r.status!=='отменено'))return{ok:false,error:'Это время уже занято.'};const id='v'+Date.now(),title=(p.lastName||'')+' '+p.name+(p.procedure?' — '+p.procedure:''),desc=['Телефон: '+p.phone,p.note?'Заметка: '+p.note:'',p.price?'Сумма: '+p.price:''].filter(Boolean).join('\n'),eid=event(p.date,p.time,title,desc);add({id,createdAt:new Date().toISOString(),date:p.date,time:p.time,name:p.name,lastName:p.lastName||'',phone:p.phone,tooth:p.tooth||'',procedure:p.procedure||'',note:p.note||'',price:p.price||'',status:'новая',calendarEventId:eid,source});return{ok:true,id}}finally{l.releaseLock()}}
function event(date,time,title,description){const c=CalendarApp.getCalendarById(CALENDAR_ID);if(!c)throw new Error('Календарь не найден — проверь CALENDAR_ID.');let q=time.split(':').map(Number),s=new Date(date+'T00:00:00');s.setHours(q[0],q[1],0,0);return c.createEvent(title,s,new Date(s.getTime()+SLOT_MINUTES*60000),{description}).getId()}
function del(id){if(!id)return;try{let e=CalendarApp.getCalendarById(CALENDAR_ID).getEventById(id);if(e)e.deleteEvent()}catch(x){}}
function cancel(p){let r=byId(p.id);if(!r)return{ok:false,error:'Запись не найдена.'};patch(r._row,{status:'отменено'});del(r.calendarEventId);return{ok:true}}
function reschedule(p){let r=byId(p.id);if(!r)return{ok:false,error:'Запись не найдена.'};if(rows().some(x=>x.id!==r.id&&x.date===p.date&&x.time===p.time&&x.status!=='отменено'))return{ok:false,error:'Это время уже занято.'};del(r.calendarEventId);let eid=event(p.date,p.time,(r.lastName||'')+' '+r.name+(r.procedure?' — '+r.procedure:''),'Телефон: '+r.phone+'\n'+(r.note||''));patch(r._row,{date:p.date,time:p.time,calendarEventId:eid});return{ok:true}}
function updateVisit(p){let r=byId(p.id);if(!r)return{ok:false,error:'Запись не найдена.'};patch(r._row,{tooth:p.tooth||'',procedure:p.procedure||'',note:p.note||'',price:p.price||''});return{ok:true}}
function clean(r){let c=Object.assign({},r);delete c._row;return c}function listVisits(p){return{ok:true,data:rows().filter(r=>r.date===p.date).sort((a,b)=>String(a.time).localeCompare(String(b.time))).map(clean)}}function searchPatient(p){if(!p.phone)return{ok:false,error:'Укажите телефон.'};let a=rows().filter(r=>String(r.phone).includes(p.phone));if(!a.length)return{ok:true,data:{found:false}};let x=a[a.length-1];return{ok:true,data:{found:true,name:x.name,lastName:x.lastName,visits:a.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(clean)}}}